#!/usr/bin/env bash
# Self-host the site's webfonts.
#
# Pulls the woff2 files Google Fonts serves for the families listed below,
# drops them in public/assets/fonts/, and writes public/css/fonts.css with
# @font-face rules pointing at the local copies. site.css @imports that file,
# so the site has no third-party font dependency: faster first paint, nothing
# to leak to Google, and it renders identically offline.
#
# Re-run after changing FAMILIES. Requires curl.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
FONTDIR="$ROOT/public/assets/fonts"
OUTCSS="$ROOT/public/css/fonts.css"

# Google Fonts css2 query — edit here to change the type system.
FAMILIES="family=Jost:wght@200;300;400;500&family=Cormorant+Garamond:wght@300;400"

# A modern UA is required or Google serves legacy ttf instead of woff2.
UA="Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0 Safari/537.36"

mkdir -p "$FONTDIR"
echo "Fetching font CSS…"
CSS="$(curl -fsSL -H "User-Agent: $UA" "https://fonts.googleapis.com/css2?${FAMILIES}&display=swap")"

{
  echo "/* Self-hosted webfonts — generated by scripts/fetch-fonts.sh. Do not edit by hand. */"
} > "$OUTCSS"

# Walk the CSS, download each src url, and rewrite it to a local path.
printf '%s\n' "$CSS" | while IFS= read -r line; do
  if [[ "$line" =~ url\((https://[^\)]+)\) ]]; then
    URL="${BASH_REMATCH[1]}"
    # Name the file from the family + weight already parsed out of the block.
    BASE="$(basename "${URL%%\?*}")"
    if [ ! -f "$FONTDIR/$BASE" ]; then
      curl -fsSL -H "User-Agent: $UA" "$URL" -o "$FONTDIR/$BASE"
      echo "  ↓ $BASE"
    fi
    line="${line//$URL/../assets/fonts/$BASE}"
  fi
  printf '%s\n' "$line" >> "$OUTCSS"
done

echo "Wrote $(grep -c '@font-face' "$OUTCSS") @font-face rules to public/css/fonts.css"
echo "Fonts in $FONTDIR: $(ls -1 "$FONTDIR" | wc -l | tr -d ' ') files"
